Add new option (-x, --distribution) to override target distribution (Debian only)

diff --git a/bin/ignsdk-app-builder b/bin/ignsdk-app-builder
--- a/bin/ignsdk-app-builder
+++ b/bin/ignsdk-app-builder
@@ -12,7 +12,7 @@ if [ ! -d $DESTDIR ];then
 	mkdir $DESTDIR
 fi
 
-TEMP=`getopt -o hld:p: --long help,list,dir:,pkgname: -n 'ignsdk-app-builder' -- "$@"`
+TEMP=`getopt -o hld:p:x: --long help,list,dir:,pkgname:,distribution: -n 'ignsdk-app-builder' -- "$@"`
 
 eval set -- "$TEMP"
 
@@ -27,6 +27,7 @@ Options:
 	-p, --pkgname		Project Package name
 	-d, --dir		Project directory
 	-l, --list		List existing project
+	-x, --distribution	Override target distribution (Debian only)
 
 Examples:
 		
@@ -99,6 +100,15 @@ while true; do
 			;;
 		-l | --list )
 			LIST=true
+			shift
+			;;
+		-x | --distribution )
+			if [ ! "$2" == "ign" -a $DISTCHK == "debian" ]; then
+				echo "Invalid/unsupported distribution: $2"
+				exit 1
+			else
+				DIST=$2
+			fi
 			shift
 			;;
 		-- )
diff --git a/bin/ignsdk-app-creator b/bin/ignsdk-app-creator
--- a/bin/ignsdk-app-creator
+++ b/bin/ignsdk-app-creator
@@ -13,7 +13,7 @@ if [ ! -d $DESTDIR ];then
 	mkdir $DESTDIR
 fi
 
-TEMP=`getopt -o hp:gr: --long help,pkgname:,git,remote:,no-packaging -n 'ignsdk-app-creator' -- "$@"`
+TEMP=`getopt -o hp:gr:x: --long help,pkgname:,git,remote:,no-packaging,distribution: -n 'ignsdk-app-creator' -- "$@"`
 
 eval set -- "$TEMP"
 
@@ -29,6 +29,7 @@ Option :
 	-g, --git		Initialize Git repository
 	-r, --remote		Set Git remote URL
 	--no-packaging		Skip packaging process
+	-x, --distribution	Override target distribution (Debian only)
 	-h, --help		Show this help
 
 Example:
@@ -118,6 +119,15 @@ while true; do
 			;;
 		--no-packaging )
 			PACKAGING=false
+			shift
+			;;
+		-x | --distribution )
+			if [ ! "$2" == "ign" -a $DISTCHK == "debian" ]; then
+				echo "Invalid/unsupported distribution: $2"
+				exit 1
+			else
+				DIST=$2
+			fi
 			shift
 			;;
 		-h | --help )
